# Copyright HeteroCL authors. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details

version: 2
jobs:
  build:
    working_directory: ~/hcl-dialect
    docker:
      - image: zzzdavid/llvm-project:15.0.0
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    resource_class: large
    steps:
      - checkout  # checkout source code to working directory
      - run:
          name: Build HCL-MLIR
          command: |
            export BUILD_DIR=/home/circleci/llvm-project/build
            export PREFIX=/home/circleci/llvm-project/build
            mkdir -p build && cd build
            cmake -G "Unix Makefiles" .. \
                -DMLIR_DIR=$PREFIX/lib/cmake/mlir \
                -DLLVM_EXTERNAL_LIT=$BUILD_DIR/bin/llvm-lit \
                -DPYTHON_BINDING=ON \
                -DPython3_EXECUTABLE=`which python3`
            make -j4
            export PYTHONPATH=$(pwd)/tools/hcl/python_packages/hcl_core:${PYTHONPATH}
      - run:
          name: Formatting Check
          command: |
            python3 -m pip install clang-format
            bash ./.circleci/task_format.sh
      - run:
          name: Test
          command: |
            cd build
            cmake --build . --target check-hcl